### PR TITLE
 Fix 'paused' property never being true (close #1047)

### LINKED ISSUE #1047: Fix 'paused' property never being true
**Describe the bug**
`paused` is never true in `com.snowplowanalytics.snowplow/media_player/jsonschema/1-0-0`

### PR DESCRIPTION
**Pull request by greg-el**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

File: plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts [hunk 1]
```diff
@@ -74,7 +74,7 @@ function getMediaPlayerEntities(
 ): MediaEntities {
   const playerStates: Record<string, boolean> = {
     ended: false,
-    paused: false,
+    pause: false,
```
Comment (paulboocock) [inline plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts:77]: Would it read better to make the change to the `YTStateEvent` enum in `constants.ts` so it can remain as `paused` here? That aligns better with the Youtube API docs:
Screenshot 2022-01-27 at 11 28 50

**Review by paulboocock — COMMENTED** [review]
Just one comment here, bit of a nit pick but might read better.

File: plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts [hunk 2]
```diff
@@ -73,22 +73,22 @@ function getMediaPlayerEntities(
   eventData?: EventData
 ): MediaEntities {
   const playerStates: Record<string, boolean> = {
-    ended: false,
-    paused: false,
+    [YT.PlayerState.ENDED]: false,
+    [YT.PlayerState.PAUSED]: false,
```
Comment (paulboocock) [inline plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts:77]: This feels a little weird to me as using numbers as keys in an object feels a bit strange (and now wrongly typed). Its an enum (and a number), so should be `Record<number, boolean>`. However , I'm not particularly picky as we used to map the number to a the string in the previous commit which I don't see is any real difference. Maybe just fix the type.

This function is now also quite different to `getYouTubeEntities` above, however it has the same behaviour. It'd be nice to make them consistent.

File: plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts [hunk 3]
```diff
@@ -22,26 +21,26 @@ export function buildYouTubeEvent(player: YT.Player, eventName: string, conf: Tr
 function getYouTubeEntities(player: YT.Player, urlParameters: UrlParameters, eventData?: EventData): MediaEntities {
   const spherical: YT.SphericalProperties = player.getSphericalProperties();
   const playerStates: Record<string, boolean> = {
```
Comment (paulboocock) [inline plugins/browser-plugin-youtube-tracking/src/buildYouTubeEvent.ts:23]: `number`

**Review by paulboocock — APPROVED** [review]
