### PR TITLE
Export MediaEventType from media plugin (Close #1315)

### LINKED ISSUE #1315: Export `MediaEventType` from media plugin
**Describe the bug**

 The MediaEventType type is not exported from the plugin although it is used in the public API of the plugin. 

**Expected behavior**
We should export it.

### PR DESCRIPTION
**Pull request by Jack-Keene**

### CODE REVIEW

File: plugins/browser-plugin-media/src/api.ts [hunk 1]
```diff
@@ -396,7 +396,9 @@ export function trackMediaAdSkip(
   trackers: Array<string> = Object.keys(_trackers)
 ) {
   let { percentProgress } = args;
-  if (percentProgress !== undefined) { percentProgress = Math.floor(percentProgress); }
```
Comment (greg-el) [inline plugins/browser-plugin-media/src/api.ts:399]: Can you remove these styling changes from the PR?

**Review by greg-el — APPROVED** [review]
LGTM

File: plugins/browser-plugin-media/src/api.ts (hunk 1 above)
Comment (Jack-Keene) [reply plugins/browser-plugin-media/src/api.ts:399]: It does this on the Pre-commit CI now, so not really!
